"""Derive recompiler function seeds from an assembled SPA disassembly listing.

Input is the AS listing (Main.lst) produced by assembling ValleyBell's SPA
disassembly (see docs/recomp-plan.md). The output is committed as
config/recomp/functions.txt: one "ADDRESS NAME" line per routine entry point
(labels that are called, have their address taken, or start an IDA
subroutine). Addresses are facts about the ROM; no code or data is copied.

It also writes out/recomp/listing_instructions.txt (address, size and text of
every instruction) for checking the recompiler's decoder. That file stays
local.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

LINE = re.compile(r"^\(\d+\)\s*\d+/\s*([0-9A-F]+) : ((?:[0-9A-F]{2} )*)\s*(.*)$")
CONTINUATION = re.compile(r"^\s+((?:[0-9A-F]{2} )+)\s*$")
LABEL = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):(.*)$")
DATA_DIRECTIVES = {"DB", "DW", "DD", "D3", "DC", "DS", "db", "dw", "dd", "ALIGN", "align", "BINCLUDE", "INCLUDE"}
# IDA marks each xref with an arrow glyph (0x18 up / 0x19 down) before its
# kind letter: p = call, j = jump, o = address taken, r/w = data access.
XREF_TOKEN = re.compile(r"([A-Za-z_0-9:+\-]+?)[\x18\x19]?([pjorw])(?=\s|$|,)")


def parse(listing: Path):
    labels: dict[str, tuple[int, str]] = {}
    instructions: dict[int, tuple[int, str]] = {}
    subroutine_pending = False
    last_label: str | None = None
    last_instruction: int | None = None
    for raw in listing.read_text(encoding="latin-1").splitlines():
        m = LINE.match(raw)
        if not m:
            cm = CONTINUATION.match(raw)
            if cm and last_instruction is not None:
                size, text = instructions[last_instruction]
                instructions[last_instruction] = (size + len(cm.group(1).split()), text)
            continue
        last_instruction = None
        address = int(m.group(1), 16)
        data = m.group(2).split()
        text = m.group(3).strip()
        if "S U B R O U T I N E" in text:
            subroutine_pending = True
            continue
        lm = LABEL.match(text)
        if lm:
            name, rest = lm.group(1), lm.group(2)
            kinds = set()
            for token in re.findall(r"XREF:([^;]*)", rest):
                kinds.update(k for _, k in XREF_TOKEN.findall(token))
            if subroutine_pending:
                kinds.add("s")
                subroutine_pending = False
            labels[name] = (address, "".join(sorted(kinds)))
            last_label = name
            continue
        if text.startswith(";") and last_label and "XREF" not in text:
            # continuation of an xref comment: "; ROM:0020023Fj ..."
            kinds = {k for _, k in XREF_TOKEN.findall(text)}
            if kinds:
                addr, old = labels[last_label]
                labels[last_label] = (addr, "".join(sorted(set(old) | kinds)))
            continue
        if not data or not text or text.startswith(";"):
            continue
        mnemonic = text.split()[0]
        if mnemonic in DATA_DIRECTIVES or mnemonic.startswith("("):
            continue
        if address not in instructions:
            instructions[address] = (len(data), " ".join(text.split(";")[0].split()))
            last_instruction = address
        last_label = None
    return labels, instructions


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("listing", type=Path)
    parser.add_argument("--functions", type=Path, default=Path("config/recomp/functions.txt"))
    parser.add_argument("--instructions", type=Path, default=Path("out/recomp/listing_instructions.txt"))
    args = parser.parse_args()

    labels, instructions = parse(args.listing)
    seeds: dict[int, str] = {}
    for name, (address, kinds) in labels.items():
        if address not in instructions:
            continue
        if {"p", "o", "s"} & set(kinds):
            seeds.setdefault(address, name)
    seeds.setdefault(0x200040, "EntryPoint")

    args.functions.parent.mkdir(parents=True, exist_ok=True)
    with args.functions.open("w", newline="\n") as out:
        out.write("# Routine entry points for the recompiler (address name).\n")
        out.write("# Generated by tools/recomp_seeds.py from the SPA disassembly listing;\n")
        out.write("# names follow ValleyBell's disassembly.\n")
        for address in sorted(seeds):
            out.write(f"{address:06X} {seeds[address]}\n")

    args.instructions.parent.mkdir(parents=True, exist_ok=True)
    with args.instructions.open("w", newline="\n") as out:
        for address in sorted(instructions):
            size, text = instructions[address]
            out.write(f"{address:06X} {size} {text}\n")
    print(f"{len(seeds)} function seeds, {len(instructions)} instructions")


if __name__ == "__main__":
    main()
