// Runtime support for recompiled TLCS-900/H code.
//
// Recompiled routines run on the interpreter's CPU object (registers, flags,
// helpers and instruction handlers are shared), one instruction per
// interpreter step. Calls and returns map onto C++ calls and returns; when the
// game leaves that structure (reloading the stack pointer, returning somewhere
// unexpected) the runtime unwinds to rt::run(), which resumes from the CPU's
// program counter, interpreting until it reaches a recompiled routine.
#pragma once

#include "ngpc/ngpc_cpu.h"

#include <cstddef>
#include <cstdint>
#include <map>

using Cpu = ngpc_cpu;

namespace rt {

using Fn = void (*)(Cpu *);

struct Entry
{
	uint32_t address;
	Fn fn;
	const char *name;
};

// Generated by spa-recomp (dispatch.cpp), sorted by address.
extern const Entry entries[];
extern const size_t entry_count;

// Thrown to abandon the current C++ call chain; rt::run() resumes at PC.
struct Unwind
{
};

struct Stats
{
	uint64_t recompiled_calls = 0;
	uint64_t interpreted_steps = 0;
	uint64_t unwinds = 0;
	uint64_t dispatch_misses = 0;
	// Addresses that had to be interpreted because no routine starts there.
	std::map<uint32_t, uint64_t> miss_addresses;
};

Stats &stats();

Fn lookup(uint32_t address);
const char *name_of(uint32_t address);

[[noreturn]] void unwind(Cpu *c, uint32_t pc);

// Runs the routine at c->m_pc.d as a call that must come back to `ret`
// with the stack pointer at `sp`.
void call(Cpu *c, uint32_t ret, uint32_t sp);

// Continues at c->m_pc.d in place of the current routine (tail jump).
void jump(Cpu *c);

// Services an interrupt accepted at the start of the instruction at `resume`.
void interrupt(Cpu *c, uint32_t resume);

void enter(Cpu *c);
void leave();
void check_return(Cpu *c, uint32_t ret, uint32_t sp);

// Executes the game from c->m_pc.d forever (until an exception other than
// Unwind leaves it).
void run(Cpu *c);

} // namespace rt

#define RC_BEGIN(address) while (c->recompiled_step_begin(address)) rt::interrupt(c, address)
#define RC_END(cycles) c->recompiled_step_end(cycles)
#define RC_CALL(fn, ret) \
	do { \
		const uint32_t rc_sp = c->m_xssp.d + 4; \
		rt::enter(c); \
		fn(c); \
		rt::leave(); \
		rt::check_return(c, ret, rc_sp); \
	} while (0)
#define RC_TAIL(fn) \
	do { \
		rt::enter(c); \
		fn(c); \
		rt::leave(); \
	} while (0)
